### PR TITLE
fix: empty white space in article detail page #27

### PR DESCRIPTION
**Pull request by patelvimal**

### CODE REVIEW

**Comment by ajitsinghkaler** [comment]
Can you add documentation to contributing.md and Readme file too abut the new commit message linting

**Comment by patelvimal** [comment]
> Thankyou for adding this. Can you add documentation to contributing.md and Readme file too about the new commit message linting

ok, will add information about conventional commit linting, however what needs to be added in readme file?

**Comment by ajitsinghkaler** [comment]
in readme add a link to contributing guidelines of how to write commit message

**Comment by patelvimal** [comment]
> in readme add a link to contributing guidelines of how to write commit message



> in readme add a link to contributing guidelines of how to write commit message

added, please review

**Comment by ajitsinghkaler** [comment]
Thanks I'll merge it

**Review by ajitsinghkaler — APPROVED** [review]
Great job Thanks for all your work

**Pull request merged**
